[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/fuel-price"
  to = "/.netlify/functions/fuel-price"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
